services:
  - type: web
    name: botzxy-c2
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
    healthCheckPath: /